name: teman_tumbuh
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/onboarding1.png
    - assets/logo.png
    - assets/onboarding2.png
    - assets/onboarding3.png
    - assets/welcome.png
    - assets/profile_picture.png
    - assets/ilustrasi_belum_tambah_anak.png
    - assets/artikel_sample.png
    - assets/baby_icon.png
    - assets/profile_picture1.png
    - assets/food_asi.png
    - assets/food_bubur_jagung.png
    - assets/google_icon.png
    - assets/facebook_icon.png
    - assets/apple_icon.png
    - assets/ubi.png
    - assets/bubur.png
    - assets/perkedel.png
    - assets/icon_vaksin.png
    - assets/icon_tumbuh.png
    - assets/icon_belanja.png
    - assets/icon_campaign.png
    - assets/artikel_sample.png
    - assets/mocobukurek.jpg
    - assets/boardgame.webp
    - assets/doktif.jpg
    - assets/dokter1.jpg
    - assets/ricard-lee.jpg
